Bump 0.5.0 rc.0 (#47)
* fix release workflow

* switch to URL type for bootstrap and signaling url, address cleanup comments

* add holochain versions note to readme

* fix typo

* fix remaining moss reference, rename to holochainPath and lairPath

* add prettierrc.yaml and reformat all files

* fix bug of enabling app if memproof provisioning deferred

* add auto updater logic

* feat: Password logic (#22)

* implemented no-password and password-required options

* added password-optional logic

* fix bundling of html pages, add additional log line

* remove unused CSS

* moved styles to shared styles

* replace uuid with nanoid

* bump kangaroo to holochain 0.4.0 (#24)

* (feat) systray option (#25)

* bump kangaroo to holochain 0.4.0

* add optional systray logic

* revert accidentally changed package name

* Clarify icon not found warning (#26)

* clarify icon not found warning

* rephrasing

* remove redundant PNG

* remove duplicate whitespace

* change icon resolution requirement

* move to macos-13 for intel

* add config write step to yarn setup

* update ziptest url

* move setup step below ziptest fetching step

* bump to holochain 0.4.1

* added missing arch appendix in dmg name (#30)

* Fix: IPC handler timing (#31)

* move get-name-and-version handler before splashscreen creation

* move all handlers above splashscreen creation

* add comment why ipc handlers are registered before splash screen creation

* fixes for a macos code signed build (#37)

* change stable in readme

* fix if statement for windows code signing (#41)

* fix systray icon name (#42)

* Fix CI not working out of the box (#43)

* add option to specify .webhapp source url in config

* better langauge

* fix if condition

* fix bash script

* specify shell type

* moved setup to make sure npm packages are installed

* move name overwrite step

* fix hash assignment

* split windows and unix

* fix bracket and filename

* move webhapp fecthing to node script

* fix fetch:webhapp command

* fix webhapp node script

* fix wrong variable

* Update scripts/fetch-webhapp.js

Co-authored-by: mattyg <matt@buildyourweb.app>

* Update scripts/fetch-webhapp.js

Co-authored-by: mattyg <matt@buildyourweb.app>

* extract downloadFile into separate file to DRY up

---------

Co-authored-by: mattyg <matt@buildyourweb.app>

* Add openLogs, exportLogs and factoryReset IPC calls (#45)

* add openLogs, exportLogs and factoryReset IPC calls

* undo appId renaming

* more renaming undo

* add ci_pass test

* fix syntax

* fix syntax

* fix typo

* add needs field

* fix namings, more granular try/catch

* remove test.yaml again

* fix formatting

* move defaultSession cache deletion to separate function, add inline comment

* consolidate if statement and remove console logs

* change factory reset message

* bump to holochain 0.5.0-rc.0

* remove dummy name

* bump to 0.5.0-rc.1

* add changelog, update readme

---------

Co-authored-by: Joel Ulahanna <joelulahanna@gmail.com>
Co-authored-by: mattyg <matt@buildyourweb.app>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -9,8 +9,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        platform: [ubuntu-22.04]
-        # platform: [windows-2019, macos-12, macos-latest, ubuntu-22.04]
+        platform: [windows-2019, macos-13, macos-latest, ubuntu-22.04]
     env:
       MACOSX_DEPLOYMENT_TARGET: 10.13
 
@@ -19,14 +18,6 @@ jobs:
     runs-on: ${{ matrix.platform }}
     steps:
       - uses: actions/checkout@v2
-
-      - name: Setup for macOS code signing
-        if: (matrix.platform == 'macos-12' || matrix.platform == 'macos-latest') && steps.shouldMacOSCodeSign.outputs.MACOS_CODE_SIGNING == 'true'
-        uses: matthme/import-codesign-certs@5565bb656f60c98c8fc515f3444dd8db73545dc2
-        with:
-          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE }}
-          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
-
       - name: setup node
         uses: actions/setup-node@v1
         with:
@@ -40,48 +31,46 @@ jobs:
         with:
           go-version: 'stable'
 
+      # This step is only used for testing in the official kangaroo repo
+      - name: Overwrite Names for release testing
+        if: ${{ github.repository }} == 'holochain-apps/kangaroo-electron'
+        run: |
+          echo ${{ github.repository }}
+          echo "overwriting names for release testing"
+          node ./scripts/overwrite-with-test-name.js
+
       - name: Environment setup
         run: |
           yarn setup
 
-      # This step is only used for testing in the official kangaroo repo
-      - name: Overwrite Names for release testing and fetch kando webhapp from github
-        if: ${{ github.repository }} == 'holochain-apps/holochain-kangaroo-electron'
+      - name: Read kangaroo config
+        shell: bash
+        id: kangarooConfig
         run: |
-          echo ${{ github.repository }}
-          echo "overwriting names for release testing"
-          curl -f -L --output ./pouch/ziptest.webhapp https://github.com/holochain-apps/ziptest/releases/download/ziptest-v0.0.9/ziptest.webhapp
-          node ./scripts/overwrite-with-test-name.js
-
-      - name: Retrieve version
-        run: |
-          echo "Retrieved App version: $(node -p -e "require('./package.json').version")"
           echo "APP_VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_OUTPUT
-        id: version
-        shell: bash
-
-      - name: Retrieve appId
-        run: |
           echo "APP_ID=$(node ./scripts/read-app-id.js)" >> $GITHUB_OUTPUT
-        id: appId
-        shell: bash
-
-      - name: Retrieve whether Windows code signing should be attempted
-        run: |
-          echo "WINDOWS_CODE_SIGNING=$(node ./scripts/read-windows-code-signing.js)" >> $GITHUB_OUTPUT
-        id: shouldWindowsCodeSign
-        shell: bash
-
-      - name: Retrieve whether macOS code signing should be attempted
-        run: |
           echo "MACOS_CODE_SIGNING=$(node ./scripts/read-macos-code-signing.js)" >> $GITHUB_OUTPUT
-        id: shouldMacOSCodeSign
+          echo "WINDOWS_CODE_SIGNING=$(node ./scripts/read-windows-code-signing.js)" >> $GITHUB_OUTPUT
+
+      - name: Check that webhapp is available in pouch folder
         shell: bash
+        run: |
+          if ! ls ./pouch/*.webhapp 1>/dev/null 2>&1; then
+            echo "Error: No .webhapp file found in ./pouch folder. Make sure to specify a URL to your webhapp in kangaroo.config.ts or commit the webhapp to git."
+            exit 1
+          fi
+
+      - name: Setup for macOS code signing
+        if: (matrix.platform == 'macos-13' || matrix.platform == 'macos-latest') && steps.kangarooConfig.outputs.MACOS_CODE_SIGNING == 'true'
+        uses: matthme/import-codesign-certs@5565bb656f60c98c8fc515f3444dd8db73545dc2
+        with:
+          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE }}
+          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
 
       # macOS WITHOUT code signing
       #---------------------------------------------------------------------------------------
       - name: build and upload the app WITHOUT code signing (macOS x86)
-        if: matrix.platform == 'macos-12' && steps.shouldMacOSCodeSign.outputs.MACOS_CODE_SIGNING == 'false'
+        if: matrix.platform == 'macos-13' && steps.kangarooConfig.outputs.MACOS_CODE_SIGNING == 'false'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           CSC_IDENTITY_AUTO_DISCOVERY: false
@@ -90,7 +79,7 @@ jobs:
           ls dist
 
       - name: build and upload the app WITHOUT code signing (macOS arm64)
-        if: matrix.platform == 'macos-latest' && steps.shouldMacOSCodeSign.outputs.MACOS_CODE_SIGNING == 'false'
+        if: matrix.platform == 'macos-latest' && steps.kangarooConfig.outputs.MACOS_CODE_SIGNING == 'false'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           CSC_IDENTITY_AUTO_DISCOVERY: false
@@ -102,7 +91,7 @@ jobs:
       #---------------------------------------------------------------------------------------
       # Note this issue regarding the if condition: https://github.com/actions/runner/issues/1173
       - name: build and upload the app WITH code signing (macOS x86)
-        if: matrix.platform == 'macos-12' && steps.shouldMacOSCodeSign.outputs.MACOS_CODE_SIGNING == 'true'
+        if: matrix.platform == 'macos-13' && steps.kangarooConfig.outputs.MACOS_CODE_SIGNING == 'true'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           APPLE_DEV_IDENTITY: ${{ secrets.APPLE_DEV_IDENTITY }}
@@ -115,7 +104,7 @@ jobs:
           ls dist
 
       - name: build and upload the app WITH code signing (macOS arm64)
-        if: matrix.platform == 'macos-latest' && steps.shouldMacOSCodeSign.outputs.MACOS_CODE_SIGNING == 'true'
+        if: matrix.platform == 'macos-latest' && steps.kangarooConfig.outputs.MACOS_CODE_SIGNING == 'true'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           APPLE_DEV_IDENTITY: ${{ secrets.APPLE_DEV_IDENTITY }}
@@ -139,9 +128,8 @@ jobs:
 
           # Modify the postinst script of the .deb file
           node ./scripts/extend-deb-postinst.mjs
-          gh release upload "v${{ steps.version.outputs.APP_VERSION }}" "latest-linux.yml" --clobber
-          gh release upload "v${{ steps.version.outputs.APP_VERSION }}" "dist/${{ steps.appId.outputs.APP_ID }}_${{ steps.version.outputs.APP_VERSION }}_amd64.deb" --clobber
-
+          gh release upload "v${{ steps.kangarooConfig.outputs.APP_VERSION }}" "latest-linux.yml" --clobber
+          gh release upload "v${{ steps.kangarooConfig.outputs.APP_VERSION }}" "dist/${{ steps.kangarooConfig.outputs.APP_ID }}_${{ steps.kangarooConfig.outputs.APP_VERSION }}_amd64.deb" --clobber
 
       # Windows
       #---------------------------------------------------------------------------------------
@@ -155,7 +143,7 @@ jobs:
           ls dist
 
           # If Windows EV code signing is set to true in kangaroo.config.ts, do code signing here
-          if [ "${{steps.shouldWindowsCodeSign.output.WINDOWS_CODE_SIGNING}}" == true ]; then
+          if [ "${{ steps.kangarooConfig.outputs.WINDOWS_CODE_SIGNING }}" == "true" ]; then
 
             # Assumes this setup of EV certificates:
             # https://melatonin.dev/blog/how-to-code-sign-windows-installers-with-an-ev-cert-on-github-actions/
@@ -163,20 +151,20 @@ jobs:
             # Sign the .exe file
             dotnet tool install --global --version 4.0.1 AzureSignTool
             echo "sha512 before code signing"
-            CertUtil -hashfile "dist/${{ steps.appId.outputs.APP_ID }}-${{ steps.version.outputs.APP_VERSION }}-setup.exe" SHA512
-            AzureSignTool sign -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}" -kvi "${{ secrets.AZURE_CLIENT_ID }}" -kvt "${{ secrets.AZURE_TENANT_ID }}" -kvs "${{ secrets.AZURE_CLIENT_SECRET }}" -kvc ${{ secrets.AZURE_CERT_NAME }} -tr http://timestamp.digicert.com -v "dist/${{ steps.appId.outputs.APP_ID }}-${{ steps.version.outputs.APP_VERSION }}-setup.exe"
+            CertUtil -hashfile "dist/${{ steps.kangarooConfig.outputs.APP_ID }}-${{ steps.kangarooConfig.outputs.APP_VERSION }}-setup.exe" SHA512
+            AzureSignTool sign -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}" -kvi "${{ secrets.AZURE_CLIENT_ID }}" -kvt "${{ secrets.AZURE_TENANT_ID }}" -kvs "${{ secrets.AZURE_CLIENT_SECRET }}" -kvc ${{ secrets.AZURE_CERT_NAME }} -tr http://timestamp.digicert.com -v "dist/${{ steps.kangarooConfig.outputs.APP_ID }}-${{ steps.kangarooConfig.outputs.APP_VERSION }}-setup.exe"
             echo "sha512 after code signing"
-            CertUtil -hashfile "dist/${{ steps.appId.outputs.APP_ID }}-${{ steps.version.outputs.APP_VERSION }}-setup.exe" SHA512
+            CertUtil -hashfile "dist/${{ steps.kangarooConfig.outputs.APP_ID }}-${{ steps.kangarooConfig.outputs.APP_VERSION }}-setup.exe" SHA512
 
             # Overwrite the latest.yml one with one containing the sha512 of the code signed .exe file
             node ./scripts/latest-yaml.js
-            gh release upload "v${{ steps.version.outputs.APP_VERSION }}" "latest.yml" --clobber
-            gh release upload "v${{ steps.version.outputs.APP_VERSION }}" "dist/${{ steps.appId.outputs.APP_ID }}-${{ steps.version.outputs.APP_VERSION }}-setup.exe" --clobber
+            gh release upload "v${{ steps.kangarooConfig.outputs.APP_VERSION }}" "latest.yml" --clobber
+            gh release upload "v${{ steps.kangarooConfig.outputs.APP_VERSION }}" "dist/${{ steps.kangarooConfig.outputs.APP_ID }}-${{ steps.kangarooConfig.outputs.APP_VERSION }}-setup.exe" --clobber
 
           fi
 
       - name: Merge latest-mac.yml mac release files
-        if: matrix.platform == 'macos-latest' || matrix.platform == 'macos-12'
+        if: matrix.platform == 'macos-latest' || matrix.platform == 'macos-13'
         run: |
           node ./scripts/merge-mac-yamls.mjs
         env:
